name: Creative
version: '1.2'
main: timeplay.creativecoding.Main
api-version: 1.16
authors: [ TimePlay ]
description: Let players create the worlds
commands:
  creativecoding:
    usage: /creativecoding
    aliases: [coding,creative]
  chat:
    usage: /creativechat
    aliases: [cc,сс]
  build:
    usage: /build
    aliases: [игшдв]
  dev:
    usage: /dev
    aliases: [develop,code,дум]
  play:
    usage: /play
    aliases: [start,здфй,ыефке]
  join:
    usage: /join
    aliases: [ощшт,id]
  ad:
    usage: /ad
    aliases: [фв]
  like:
    usage: /like
    aliases: [дшлу, vote, v]
  spawn:
    usage: /spawn
    aliases: [спавн, ізфцт, ызфцт, hub, lobby]
  menu:
    usage: /menu
    aliases: [меню, games, worlds, ьутг, minigames]
  settings:
    usage: /settings
    aliases: [world, game, іуеештпі, ыуеештпы, setting]